### PR TITLE
Added two way text on globe

### PR DESCRIPTION
**Pull request by DanCRichards**
Hey from New Zealand 
Awesome project! 👍 

I've added the functionality for two way text. This has been done by simply cloning the text object, rotating it and changing the shader to include: `Cull Back`.
This means you can read the cities from both left and right.

Excuse all the whitespace changes, my CodeMaid plugin likes to do that.... 

Cheers, 
Dan

### CODE REVIEW

**Comment by cre8ivepark** [comment]
Thanks for the awesome improvements!
Could you please exclude unrelated changes? (e.g. files under ProjectSettings)

**Review by cre8ivepark — CHANGES_REQUESTED** [review]
Thanks for the awesome improvements!
Could you please exclude unrelated changes? (e.g. files under ProjectSettings)

**Comment by DanCRichards** [comment]
Yeah of course. Cheers.

**Comment by DanCRichards** [comment]
I've changed it so that only the required changes are showing on the pull request. 

Works fine on my pull request, although I didn't have to change the text material to be `Cull back`, which I remember I had to do originally. Please give it a test on your end :)

**Comment by cre8ivepark** [comment]
Thanks for the update!

**Pull request merged**
